remote_theme: pmarsceill/just-the-docs
title: La sfida Gygax 75
description: >-
  Crea un'ambientazione di campagna GDR in cinque settimane!
  La sfida Gygax 75 di Ray Otus, è rilasciato sotto licenza Attribution-ShareAlike 4.0 International